version: '2'
services:
  app1_presentation:
    build:
      context: ./
      dockerfile: Dockerfile.app1
    ports:
      - "8081:80"
  app2_demosite:
    build:
      context: ./
      dockerfile: Dockerfile.app2
    ports:
      - "8082:80"
